apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: website

spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: flask-website
        image: ahervias77/flask-website:k8s-test-1
        ports:
        - containerPort: 5000
         